### ISSUE TITLE
Update to RESTful

### ISSUE THREAD

**Issue by Nathanrs97** [sufst/wireless-telemetry-gui#7]
### 1. Please describe the feature you are trying to request.
- The front-end protocol should be updated to interface with the intermediate server's RESTful API over a WebSockets.

### 2. Describe the solution you'd like.
- The front-end GUI should utilise WebSockets to interface with the intermediate server over the RESTful API provided by the server.
- Any issues with the RESTful API (or enhancements that would benefit the API) should be commented here.
- At the time of this issue only the `amount` filter has been implemented in the intermediate server. This should be used initially until the `timesince` filter has been implemented and is ready for use.
- Once this issue has been resolved, a corresponding issue on the intermediate server should be raised to remove the previous TCP implementation since it is no longer required.

**Comment by AndreasDemenagas** [comment]
I will begin working on this this week, with the hope that I will be able to integrate the basic changes quite quickly and easily (I already have a demo project setup working on Node.js and the WebSocket from the intermediate server 😛)

**Comment by AndreasDemenagas** [comment]
Here is the approach I am taking: I will use RPM as an example but hopefully - if proven to work - this method will be used for all sensors. 

- I am starting with an empty array - named `rpm` for example. 
- When the app initially launches, I am requesting the data for the last 5 seconds using the `timesince` param and putting that in the `rpm` array.
- Then I am requesting the data from the server every 1 second, using the `timesince` param with the current epoch time. minus 1 second (since this is the all the data I have missed between the calls). 
- I take all the data returned from the last second and append it (concatenate) it to the `rpm` array. 

In the end, the RPM array holds all the data that the car has sent for the RPM sensor.

**Comment by AndreasDemenagas** [comment]
As I was writing the above, I thought that using that approach I would still need to do some hacky array manipulation to limit the values of the `rpm` array within the limit of the data we need to graph. 

So, I think I will move to the `/sensors?amount=<n>` method that will return the last `n` value for the sensors. That way the server & parsing code can be downscaled by a bit. Here is what I am thinking: 

- When the app starts we call the `/sensors?amount=<n>` endpoint which returns the needed amount of points for each graph. 
- After 1 second - or the time we decide to refresh - we call the same endpoint again and replace the array of data from the previous call with the ones from this more recent call. Since the most recent call will return the most recent data, then we don't have to manipulate the arrays returned at all in the front-end. 
- So - hopefully - we can just take the array returned from the `/sensors?amount=<n>` call and graph it automatically. 

@Nathanrs97 Can you please confirm what the `/sensors?amount=<n>` call returns if the available data points are less that the specified n? I guess if I request the last 20 points but the car has only sent 10 values, the `/sensors?amount=<n>`  call will just return the 10 points available there.

**Comment by Nathanrs97** [comment]
> So, I think I will move to the /sensors?amount=<n> method that will return the last n value for the sensors. That way the server & parsing code can be downscaled by a bit. Here is what I am thinking:

I would suggest using both filters still `amount=<n>&timesince=<epoch>`.
- This is because if the server has just loaded and the front-end requests e.g. 50 data points, there is a high chance you will get data points that correspond to a previous run (as the database is constant on disc). I would imagine you don't want data points that correspond to e.g. a run a month ago.
- So, at startup do e.g. `GET /sensors?amount=50&timesince={epoch - 50}` as this ensures you won't get data from a week ago.

> @Nathanrs97 Can you please confirm what the /sensors?amount=<n> call returns if the available data points are less that the specified n? I guess if I request the last 20 points but the car has only sent 10 values, the /sensors?amount=<n> call will just return the 10 points available the

Correct. The `amount` is an up-to amount. If there are only 10 data points available to return then it will return only 10 data points.

**Comment by Nathanrs97** [comment]
> Here is the approach I am taking: I will use RPM as an example but hopefully - if proven to work - this method will be used for all sensors.

I wouldn't recommend just doing epoch - 1 as I doubt JavaScript is real-time, so there is a chance (especially if you're using a timer event to trigger every 1 second) that the 1-second intervals may be between 0.9 - 1.1 seconds (e.g. worst-case scenario). 

- There is less chance of missing data because of this if you record the epoch time that corresponds to the latest data point received from the server. Then, use that as the epoch time in the next `GET` to ensure you do not miss any data.
- This could be done through the RESTful API where when you do `GET /sensors?...` there is a static entry in the returned data that gives you the time the data is up to e.g. `{ "Core": {..}, ..., "Epoch": <time>}`. This way you don't have to manipulate the arrays to work this out, the server gives you it and you just save the `<time>` locally and pass that in the next `GET` request.

Thoughts?

**Comment by AndreasDemenagas** [comment]
I will get into doing more testing and sees whether the `amount=` param will produce any problems. I haven't thought of the real-time aspect of JS tbh.

Having an epoch field in the returned JSON would be a solution - although I can't really think of a way to implement the fetching out of my head right now. This is surely worth experimenting with. 

However, as multiple sensors can have different epoch times in a JSON response, if you only save the latest one as the last epoch, won't that raise an issue where some sensor data that are between the last epoch of that sensor and the last general epoch will be lost and never fetched?

**Comment by AndreasDemenagas** [comment]
Also, I noticed  the `?amount=` filter returns the array with the most recent points first. (The newest data points are in the first indices of the array). Is there a quick way to reverse this - since if you thing about graphing - we need the latest / most recent points to be in the end of the array. 

I call always reverse the array in the front-end, but I am just mentioning this here for the sake of the intermediate server being more "fitted" to the specification of the front-end

**Comment by Nathanrs97** [comment]
> However, as multiple sensors can have different epoch times in a JSON response, if you only save the latest one as the last epoch, won't that raise an issue where some sensor data that are between the last epoch of that sensor and the last general epoch will be lost and never fetched?

Yeah, I noticed this issue too which I why I think the best solution is the `Epoch` field in the response return.

> although I can't really think of a way to implement the fetching 

I don't understand, what do you mean fetching?

I think the `epoch` field in the return response is best as then you could implement a feature where you can disable the automatic refreshing of the data on the front end (if someone wants to pause it and look at the graphs for a while) and then possibly do a manual refresh (which just uses the recorded `epoch` time saved from the last response).

**Comment by Nathanrs97** [comment]
> Also, I noticed the ?amount= filter returns the array with the most recent points first. (The newest data points are in the first indices of the array). Is there a quick way to reverse this - since if you thing about graphing - we need the latest / most recent points to be in the end of the array.

I can reverse the order that's fine. I'll raise this as an issue on the server side.

**Comment by AndreasDemenagas** [comment]
I am currently hitting `GET /sensors?amount=20&timesince=${epoch}` every 1 second, with `epoch` being the current epoch time minus 2 minutes (in order to avoid the issue of the getting data from previous runs that you mentioned)

This allow me to get the response from the server (that's what I meant by "fetch") and have it in a ready to plot format. 

I don't know if this is the best way to go - but it seems to work fine for now - so I think I will stay with this.

**Comment by Nathanrs97** [comment]
> I don't know if this is the best way to go - but it seems to work fine for now - so I think I will stay with this.

Sounds like a good approach to me. Then I'm assuming you don't record the data locally for exporting to `.csv` and instead keep track of the epoch when the front-end was started and will do a big `GET` request during export to get all data since the GUI started?

**Comment by AndreasDemenagas** [comment]
> Then I'm assuming you don't record the data locally for exporting to .csv and instead keep track of the epoch when the front-end was started and will do a big GET request during export to get all data since the GUI started?

 Yes that's what I am thinking. I will move into the CSV later today after I finish all the server parsing (already 99% complete 😛). I have to say this RESTful approach was an incredible idea. The server code on the front-end is almost not there 😂 and this will also make things like the CSV export so much easier.

**Comment by AndreasDemenagas** [comment]
@Nathanrs97 Here it is working with a dummy graph!! Any thoughts and/or ideas?

https://user-images.githubusercontent.com/55033328/110506197-8caf8780-8107-11eb-9599-6a96eb071af2.mov

**Comment by Nathanrs97** [comment]
Looks amazing! I would suggest (looking at the kind of jumpiness in the graph) keep a buffer of data so the graph looks like its fluid.

This can be achieved by doing a `GET` request not once you've run out of data to plot (assuming you don't plot the whole data array at once on the `GET` response and instead drip-feed the graph core) but instead just before you run out of data. This way, the graph can be continuously drip-fed with data from the server to make it look fluid even though you are pulling data every second or so (better user experience this way).

**Comment by Nathanrs97** [comment]
I imagine you already have this on your todo, but convert the epoch times to real date-times (like hour:minute:seconds) instead of the not-so-user friendly epoch time.

**Comment by AndreasDemenagas** [comment]
So, current I am getting the data from the GET request and  plotting all of it straight away - probably that's the reason behind the not so smouth graph. 

Being completely honest I didn't really understand what you meant by keeping a buffer and drip feeding the graph. Could you please elaborate more on that - when you have the time of course. 

Yes yes, converting the epoch times to something more readable is on my list 😂

**Comment by Nathanrs97** [comment]
> Being completely honest I didn't really understand what you meant by keeping a buffer and drip feeding the graph. Could you please elaborate more on that - when you have the time of course.

Hmm thinking out it, it probably isn't worth it as it will make the software more complex on the front-end (up to you to decide if its something you want to do). But basically, say you want to refresh the graph every 200ms but you only retrieve data every 1s, then here you can create 5 buffers of data (so 5x200ms data buffers) and then feed the graph each of these buffers every 200ms to make the graph smoother. But to play it safe you would want to always keep 1 buffer ahead of the graph for network latency to ensure the graph can also be fed a buffer every 200ms.

**Comment by AndreasDemenagas** [comment]
Ohh okay I see what you mean. Yes I will check this out - although it feels more complicated than what I can handle haha. Current, I retrieve the data every 1s then the graphs are updated automatically - every time there is new data, so every 1s. Since the emulator from the servers splits new data frames for each group every about 1 second or so I think it is safer to keep the development on this 1s refresh rate. 

Obviously, with a real car data will be sent faster than every 1s so we can then adjust the refresh rates to accommodate the server sending more data (since the real car will be logging way more frequently than the emulator) What do you think?

**Comment by Nathanrs97** [comment]
I would say at this stage spending development time on making the graphs that little bit more pretty isn't worth it, there are more important features required that will take time. 

Make the refresh rate configurable in the UI (but default it to 1s) so then we could play around and see what refresh rate provides the best experience. The car logs data every 20ms (50Hz) so you could set the emulator to that (the emulator config can take a float of 0.02) and then see how the graphs perform and look at that real logging rate.

**Comment by Nathanrs97** [comment]
@AndreasDemenagas Do you still want the array order reversed of the sensor data (as it looks like you've got it to work without it being reversed)?

**Comment by AndreasDemenagas** [comment]
I am reversing the array right before the graphing. Ideally I think it would be better to have it reversed straight from the server - but if that's an issue I can keep reversing them after they are fetched from the server.

**Comment by Nathanrs97** [comment]
> I am reversing the array right before the graphing. Ideally I think it would be better to have it reversed straight from the server - but if that's an issue I can keep reversing them after they are fetched from the server.

That's fine I was just checking to incase you didn't need it reversed any more. 

The whole idea of the server is to carry out most of the data processing so the front-end doesn't need to, so this type of thing is exactly what it's designed for.
